#!/usr/bin/env bash
# Local validator with the mainnet pump.fun account set cloned.
#
# The account list is derived, not guessed: every address here was checked to exist on mainnet
# (see README). `buyback_recipient` in particular is a 208-byte fee-program account, not a plain
# wallet, so it must be cloned rather than merely funded.
set -euo pipefail
# ⭐ Custom pairs: pump.fun's quote-control list, Jupiter, and the one PumpSwap pool per test pair
# token that the pair suite's swap routes through. Generated by fixtures/make-pair-route.mjs.
PAIR_CLONES=$(node -e 'const d=require("./fixtures/pair-route-accounts.json");console.log([...d.programs.map(p=>"--clone-upgradeable-program "+p),...d.accounts.map(a=>"--clone "+a)].join(" "))')
export PATH="$HOME/.local/share/solana/install/releases/4.0.0/solana-release/bin:$PATH"
# ⚠ launchdeck's executor binds 127.0.0.1:8899, the validator's default RPC port. The CLI would
# reach the executor first and report "method getVersion does not exist" — which reads like a
# broken validator rather than a port collision. Use a port nothing else wants.
RPC="${SOLANA_RPC_URL:?set SOLANA_RPC_URL — the public endpoint rate-limits the clone}"
PORT="${LOCAL_RPC_PORT:-8999}"
rm -rf test-ledger
# ⚠ The create_v2 / quote-mint accounts below are needed to exercise create_v2 at all. Read off a
# real USDC-quoted launch (CAA37EB8VnDD97MvDZKfHgChKbLNxD435WATp1Mgpump), not guessed: create_v2
# mints Token-2022 and appends quote_mint, its associated curve account and the quote token
# program as three accounts beyond the 16 the IDL lists.
#
# ⛔ Do NOT put a comment between these continued lines. A `\` followed by a `#` line ENDS the
# command, so everything after it — including --bpf-program — disappears and the validator comes
# up without this program. `bash -n` passes on that, because it is valid shell meaning something
# else, and the failure surfaces as a simulation error in the tests.
exec solana-test-validator \
  --url "$RPC" \
  --rpc-port "$PORT" \
  --ledger test-ledger \
  --reset \
  --quiet \
  --log-messages-bytes-limit 200000 \
  `# ⛔ The default ledger keeps ~10k shreds. The full suite outlives that: the pair suite's` \
  `# deposits were PURGED before delivery read them, and the watcher (rightly) refused to` \
  `# deliver on the short history. Mainnet reads an archival RPC; this is the clone only.` \
  --limit-ledger-size 500000000 \
  --clone-upgradeable-program 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P \
  --clone-upgradeable-program pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ \
  `# The AMM. Not used by a launch — a coin only reaches it after graduation — but` \
  `# create_fee_sharing_config declares it and Anchor checks it is EXECUTABLE, so a` \
  `# missing one fails fee sharing with "Program account is not executable".` \
  --clone-upgradeable-program pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA \
  --clone-upgradeable-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s \
  --clone 4wTV1YmiEkRvAtNtsSGPtUrqRYQMe5SKy2uB4Jjaxnjf \
  --clone Ce6TQqeHC9p8KetsN6JsjHK7UTZk7nasjjnr7XxXp9F1 \
  --clone Hq2wp8uJ9jCPsYgNHex8RtqdvMPfVGoYwjvF1ATiwn2Y \
  --clone TSLvdd1pWpHVjahSpsvCXUbgwsL3JAcvokwaKt1eokM \
  --clone 8Wf5TiAheLUqBrKXeYg2JtAFFMWtKdG2BSFgqUcPVwTt \
  --clone 62qc2CNXwrYqQScmEdiZFFAnJR262PxWEuNQtxfafNgV \
  --clone 5YxQFdt3Tr9zJLvkFccqXVUwhdTWJQc1fFg2YPbxvxeD \
  --clone-upgradeable-program MAyhSmzXzV1pTf7LsNkrNwkWKTo4ougAJ1PPg47MD4e \
  --clone 13ec7XdrjF3h3YcqBTFDSReRcUFwbCnJaAQspM4j6DDJ \
  --clone BwWK17cbHxwWBKZkUYvzxLcNQ1YVyaFezduWbtm2de6s \
  --account EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v fixtures/usdc-mint.json \
  --clone BqcWAXkSdknwQxvqXYVGKtttZynYNHACPVJmTaoqgfv8 \
  --clone 6oCkp6gpyjxVTeL6ahMYcekN2x2pzt1KY8g2LqemaTNE \
  `# ── the swap venue ──────────────────────────────────────────────────────────────────` \
  `# Buyers pay USDC and the coin launches on a SOL curve, so the raise is swapped through` \
  `# Raydium AMM v4 at the close. Without these the swap cannot be exercised at all, and` \
  `# neither can crediting: a buy is QUOTED at this pool's spot, so credit reads it too.` \
  `# The market's event queue is a megabyte; that is what it costs to have the real thing.` \
  --clone-upgradeable-program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 \
  --clone-upgradeable-program srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX \
  --clone 58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2 \
  --clone DQyrAcCrDXQ7NeoqGgDCZwBvWDcYmFCjSb9JtteuvPpz \
  --clone HLmqeL62xR1QoZ1HKKbXRrdN1p3phKpxRMb2VVopvBBz \
  --clone 5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1 \
  --clone HmiHHzq4Fym9e1D4qzLS6LDDM3tNsCTBPDWHTLZ763jY \
  --clone CZza3Ej4Mc58MnxWA385itCC9jCo3L1D7zc3LKy1bZMR \
  --clone 8BnEgHoWFysVcuFFX7QztDmzuH8r5ZFvyP3sYwn1XTh6 \
  --clone 5jWUncPNBMZJ3sTHKmMLszypVkoRK6bfEQMQUHweeQnh \
  --clone EaXdHx7x3mdGA38j5RSmKYSXMzAFzzUXCLNBEDXDn1d5 \
  --clone 8CvwxZ9Db6XbLD46NZwwmVDZZRDy7eydFcAGkXKh9axa \
  --clone CKxTHwM9fPMRRvZmFnFoqKNd9pQR21c5Aq9bh5h9oghX \
  --clone 6A5NHCj1yF6urc9wZNe6Bcjj4LVszQNj5DwAWG97yzMu \
  --clone CTz5UMLQm2SRWHzQnU62Pi4yJqbNGjgRBHqqp6oDHfF7 \
  $PAIR_CLONES \
  --bpf-program 8WkibpqR4jnkxpv8nHk9t3Rgw9L4UqECYYwiAGYnu8Hf target/deploy-test/pumpfamily.so
